# Generated by Django 3.0.4 on 2020-04-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapelinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='imageurl',
            field=models.CharField(default='default.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='scrapelinks',
            name='imageurl',
            field=models.CharField(default='defult.jpg', max_length=1000),
        ),
    ]
