# Generated by Django 3.0.4 on 2020-04-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200401_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='imageurl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='scrapelinks',
            old_name='imageurl',
            new_name='image_url',
        ),
    ]
