# Generated by Django 3.0.4 on 2020-04-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20200401_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='site_url',
            field=models.CharField(default='www.ibsplc.com', max_length=500),
        ),
    ]
