# Generated by Django 3.0.4 on 2020-04-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20200401_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='about',
            field=models.CharField(max_length=10000),
        ),
    ]
