# Generated by Django 3.0.4 on 2020-04-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20200401_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapelinks',
            name='image_url',
            field=models.CharField(default='default.jpg', max_length=5000),
        ),
    ]
